// MichiMenú — datos semanales. Maple genera una semana nueva cada semana y
// la agrega al FINAL de `weeks`; la app muestra la última. No borrar semanas
// pasadas: son el archivo ("reusar semana 3" en domingos flojos).
// Regla de porciones: e = ella (~1300 kcal/día) · u = tú (~1.5×).

const MICHI_DATA = {
  recipes: {
    "licuado-fresa": {
      t: "Licuado de kefir con fresa", emoji: "🥤", time: "5 min",
      ing: [
        { n: "Kefir casero", e: "250 ml", u: "350 ml" },
        { n: "Yogur griego natural", e: "100 g", u: "100 g" },
        { n: "Fresa congelada", e: "1 taza", u: "1 taza" },
        { n: "Avena", e: "3 cdas", u: "4 cdas" },
        { n: "Crema de cacahuate", e: "1 cdita", u: "1 cda" },
      ],
      steps: ["Todo a la licuadora.", "Licuar 30–40 segundos hasta quedar cremoso.", "Si está muy espeso, un chorrito de agua fría."],
      nutri: { e: "~350 kcal · 25 g proteína", u: "~520 kcal · 33 g proteína" },
    },
    "licuado-mango": {
      t: "Licuado de kefir con mango", emoji: "🥭", time: "5 min",
      ing: [
        { n: "Kefir casero", e: "250 ml", u: "350 ml" },
        { n: "Yogur griego natural", e: "100 g", u: "100 g" },
        { n: "Mango congelado", e: "1 taza", u: "1 taza" },
        { n: "Avena", e: "3 cdas", u: "4 cdas" },
      ],
      steps: ["Todo a la licuadora, 30–40 segundos.", "Canela encima si se antoja."],
      nutri: { e: "~340 kcal · 24 g proteína", u: "~480 kcal · 31 g proteína" },
    },
    "bowl-yogur": {
      t: "Bowl de yogur griego con manzana", emoji: "🍎", time: "5 min",
      ing: [
        { n: "Yogur griego natural", e: "200 g", u: "300 g" },
        { n: "Manzana picada", e: "1 pieza", u: "1 pieza" },
        { n: "Avena tostada en sartén seco", e: "2 cdas", u: "3 cdas" },
        { n: "Canela", e: "al gusto", u: "al gusto" },
      ],
      steps: ["Tostar la avena 2 min en sartén seco (huele a galleta).", "Armar el bowl: yogur, manzana, avena, canela."],
      nutri: { e: "~330 kcal · 22 g proteína", u: "~470 kcal · 31 g proteína" },
    },
    "hotcakes-avena": {
      t: "Hotcakes de avena (huevo escondido)", emoji: "🥞", time: "15 min",
      ing: [
        { n: "Huevo", e: "1 pieza", u: "2 piezas" },
        { n: "Avena", e: "½ taza", u: "¾ taza" },
        { n: "Plátano", e: "½ pieza", u: "½ pieza" },
        { n: "Polvo para hornear", e: "1 cdita", u: "1 cdita" },
        { n: "Canela", e: "al gusto", u: "al gusto" },
        { n: "Fresas para acompañar", e: "1 taza", u: "1 taza" },
      ],
      steps: ["Licuar huevo + avena + plátano + polvo + canela.", "Sartén antiadherente sin aceite, fuego medio.", "Salen 3–4 medianos; voltear cuando burbujeen.", "El huevo es invisible — textura de hotcake normal. 😼"],
      nutri: { e: "~350 kcal · 17 g proteína", u: "~520 kcal · 28 g proteína" },
    },
    "molletes": {
      t: "Molletes ligeros", emoji: "🍞", time: "10 min",
      ing: [
        { n: "Pan integral", e: "1 pieza", u: "2 piezas" },
        { n: "Frijoles machacados", e: "3 cdas", u: "5 cdas" },
        { n: "Queso panela rallado", e: "40 g", u: "60 g" },
        { n: "Pico de gallo (jitomate, poquita cebolla, limón)", e: "libre", u: "libre" },
      ],
      steps: ["Untar frijoles al pan, panela encima.", "Gratinar en sartén tapado u horno 5 min.", "Pico de gallo encima al servir."],
      nutri: { e: "~340 kcal · 22 g proteína", u: "~560 kcal · 35 g proteína" },
    },
    "pan-dulce": {
      t: "Pan dulce + café ☕ (el gusto de la semana)", emoji: "🥐", time: "0 min",
      ing: [
        { n: "Pan dulce favorito", e: "1 pieza", u: "1 pieza" },
        { n: "Café (solo o con chorrito de leche)", e: "1 taza", u: "1 taza" },
        { n: "Yogur griego (la proteína del día no se negocia)", e: "100 g", u: "100 g" },
      ],
      steps: ["Disfrutar sin culpa: ya está contado en la semana.", "El yogur va antes o después, como gusten."],
      nutri: { e: "~420 kcal · 14 g proteína", u: "~420 kcal · 14 g proteína" },
    },
    "pasta-atun": {
      t: "Pasta al jitomate con atún", emoji: "🍝", time: "20 min",
      ing: [
        { n: "Pasta (pesada en seco)", e: "60 g", u: "90 g" },
        { n: "Atún en lata, drenado", e: "1 lata", u: "1 lata" },
        { n: "Salsa base de jitomate (del domingo)", e: "1 taza", u: "1 taza" },
        { n: "Espinaca", e: "1 puño", u: "1 puño" },
        { n: "Queso rallado", e: "1 cda", u: "1 cda" },
      ],
      steps: ["Hervir la pasta.", "Calentar la salsa base; fundir la espinaca dentro.", "Agregar el atún, mezclar con la pasta.", "Queso espolvoreado. Sabe a Italia. 🇮🇹"],
      nutri: { e: "~490 kcal · 38 g proteína", u: "~640 kcal · 45 g proteína" },
    },
    "lomo-camote": {
      t: "Lomo de cerdo con puré de camote", emoji: "🍖", time: "15 min (lomo del domingo)",
      ing: [
        { n: "Lomo de cerdo horneado", e: "130 g", u: "200 g" },
        { n: "Camote (para el puré)", e: "1 chico", u: "1 mediano" },
        { n: "Pepino y jitomate en ensalada", e: "libre", u: "libre" },
        { n: "Limón y sal para la ensalada", e: "al gusto", u: "al gusto" },
      ],
      steps: ["Camote al micro 5–6 min, machacar con sal y tantita canela.", "Rebanar y calentar el lomo.", "Ensalada al lado."],
      nutri: { e: "~480 kcal · 38 g proteína", u: "~680 kcal · 55 g proteína" },
    },
    "lentejas-guisadas": {
      t: "Lentejas guisadas con arroz", emoji: "🍲", time: "15 min (lentejas del domingo)",
      ing: [
        { n: "Lentejas cocidas", e: "1 taza", u: "1½ tazas" },
        { n: "Zanahoria picada", e: "½ taza", u: "½ taza" },
        { n: "Espinaca", e: "1 puño", u: "1 puño" },
        { n: "Arroz cocido (del domingo)", e: "¾ taza", u: "1 taza" },
        { n: "Queso panela desmoronado", e: "40 g", u: "60 g" },
      ],
      steps: ["Guisar lentejas con la zanahoria y un cucharón de salsa base.", "Fundir la espinaca al final.", "Servir sobre el arroz, panela encima."],
      nutri: { e: "~510 kcal · 33 g proteína", u: "~690 kcal · 44 g proteína" },
    },
    "salteado-res": {
      t: "Salteado asiático de res", emoji: "🥢", time: "25 min",
      ing: [
        { n: "Bistec de res en tiras", e: "130 g", u: "200 g" },
        { n: "Champiñones rebanados", e: "1 taza", u: "1 taza" },
        { n: "Zanahoria en tiras", e: "½ taza", u: "½ taza" },
        { n: "Ejotes picados finos (modo escondido)", e: "½ taza", u: "½ taza" },
        { n: "Salsa de soya", e: "1½ cdas", u: "2 cdas" },
        { n: "Ajo picado", e: "1 diente", u: "1 diente" },
        { n: "Arroz cocido (del domingo)", e: "¾ taza", u: "1 taza" },
        { n: "Aceite", e: "1 cdita", u: "1 cdita" },
      ],
      steps: ["Sartén muy caliente: sellar la res 2 min, reservar.", "Saltear verduras 4–5 min con el ajo.", "Regresar la res, soya, 1 min más.", "Servir sobre el arroz."],
      nutri: { e: "~500 kcal · 36 g proteína", u: "~700 kcal · 52 g proteína" },
    },
    "alitas": {
      t: "ALITAS AL HORNO 🍗 (el plato estrella)", emoji: "🍗", time: "15 min manos + 40 min horno",
      ing: [
        { n: "Alitas de pollo", e: "5–6 piezas", u: "el resto de 450 g" },
        { n: "Polvo para hornear (el truco crujiente)", e: "1 cdita total", u: "—" },
        { n: "Sal y ajo en polvo", e: "al gusto", u: "al gusto" },
        { n: "Glaseado: soya + ajo, o mostaza + tantita miel", e: "1 cda", u: "1½ cdas" },
        { n: "Papas en gajos", e: "1 papa", u: "2 papas" },
        { n: "Zanahoria y pepino con limón", e: "libre", u: "libre" },
        { n: "Aceite (solo para las papas)", e: "½ cdita", u: "½ cdita" },
      ],
      steps: ["Secar las alitas MUY bien con papel — es el secreto.", "Revolcar en sal + ajo en polvo + polvo para hornear.", "Horno 220 °C sobre rejilla, 40–45 min, voltear a la mitad.", "Papas gajo en charola aparte, misma horneada.", "Barnizar con el glaseado a los últimos 5 min.", "Crujientes sin freír. Viernes de campeones."],
      nutri: { e: "~520 kcal · 32 g proteína", u: "~780 kcal · 48 g proteína" },
    },
    "camarones-ajo": {
      t: "Camarones al mojo de ajo", emoji: "🦐", time: "20 min",
      ing: [
        { n: "Camarón pelado", e: "130 g", u: "170 g" },
        { n: "Ajo picado", e: "2 dientes", u: "2 dientes" },
        { n: "Pasta (en seco) o arroz cocido", e: "60 g / ¾ taza", u: "90 g / 1 taza" },
        { n: "Aceite", e: "1 cdita", u: "1 cdita" },
        { n: "Limón y perejil o cilantro finito", e: "al gusto", u: "al gusto" },
        { n: "Ensalada de lechuga, jitomate y pepino", e: "libre", u: "libre" },
      ],
      steps: ["Dorar el ajo en el aceite a fuego bajo (sin quemar).", "Subir el fuego, camarones 2–3 min por lado.", "Limón encima, servir con pasta o arroz y ensalada."],
      nutri: { e: "~470 kcal · 35 g proteína", u: "~630 kcal · 45 g proteína" },
    },
    "tacos-lomo": {
      t: "Tacos de lomo con guacamole", emoji: "🌮", time: "15 min (lomo del domingo)",
      ing: [
        { n: "Lomo de cerdo horneado, deshebrado", e: "130 g", u: "200 g" },
        { n: "Tortillas de maíz", e: "2 piezas", u: "4 piezas" },
        { n: "Aguacate (guacamole simple)", e: "½ pieza", u: "½ pieza" },
        { n: "Nopales asados", e: "1–2 pencas", u: "1–2 pencas" },
        { n: "Limón y sal", e: "al gusto", u: "al gusto" },
      ],
      steps: ["Asar nopales en sartén o comal.", "Calentar el lomo deshebrado con un cucharón de salsa base.", "Guacamole: aguacate + limón + sal.", "Armar tacos y presumirlos."],
      nutri: { e: "~500 kcal · 37 g proteína", u: "~740 kcal · 56 g proteína" },
    },
    "quesadillas": {
      t: "Quesadillas de panela con champiñones", emoji: "🫓", time: "10 min",
      ing: [
        { n: "Tortillas de maíz", e: "2 piezas", u: "3 piezas" },
        { n: "Queso panela", e: "50 g", u: "80 g" },
        { n: "Champiñones salteados", e: "½ taza", u: "¾ taza" },
        { n: "Salsa base o pico de gallo", e: "al gusto", u: "al gusto" },
      ],
      steps: ["Saltear champiñones en sartén seco con sal.", "Armar quesadillas, dorar en comal hasta fundir."],
      nutri: { e: "~300 kcal · 19 g proteína", u: "~450 kcal · 29 g proteína" },
    },
    "tostadas-atun": {
      t: "Tostadas de atún", emoji: "🌊", time: "10 min",
      ing: [
        { n: "Tostadas horneadas", e: "2 piezas", u: "3 piezas" },
        { n: "Atún en lata, drenado", e: "1 lata", u: "1 lata" },
        { n: "Yogur griego (en vez de mayonesa)", e: "2 cdas", u: "2 cdas" },
        { n: "Jitomate picado y limón", e: "libre", u: "libre" },
      ],
      steps: ["Mezclar atún + yogur + jitomate + limón + sal.", "Montar sobre las tostadas al momento (que no se aguaden)."],
      nutri: { e: "~290 kcal · 28 g proteína", u: "~380 kcal · 34 g proteína" },
    },
    "sandwich-pavo": {
      t: "Sándwich de pavo y panela", emoji: "🥪", time: "5 min",
      ing: [
        { n: "Pan integral", e: "2 rebanadas", u: "2 rebanadas" },
        { n: "Jamón de pavo", e: "3 rebanadas", u: "4 rebanadas" },
        { n: "Queso panela", e: "30 g", u: "50 g" },
        { n: "Jitomate, lechuga, mostaza", e: "libre", u: "libre" },
      ],
      steps: ["Armar. La mostaza es gratis en calorías — generosos."],
      nutri: { e: "~310 kcal · 24 g proteína", u: "~400 kcal · 32 g proteína" },
    },
    "crema-lentejas": {
      t: "Crema de lentejas (brócoli escondido)", emoji: "🍵", time: "15 min",
      ing: [
        { n: "Lentejas cocidas (del domingo)", e: "1 taza", u: "1¼ tazas" },
        { n: "Salsa base de jitomate", e: "1 taza", u: "1 taza" },
        { n: "Brócoli", e: "2–3 flores", u: "2–3 flores" },
        { n: "Comino y sal", e: "al gusto", u: "al gusto" },
        { n: "Tortilla de maíz", e: "1 pieza", u: "2 piezas" },
      ],
      steps: ["Hervir todo junto 10 min con un poco de agua.", "Licuar TODO hasta quedar cremoso.", "Nadie detecta el brócoli. Palabra de michi. 😼"],
      nutri: { e: "~320 kcal · 20 g proteína", u: "~430 kcal · 27 g proteína" },
    },
    "yogur-fruta-pb": {
      t: "Yogur griego con fruta y cacahuate", emoji: "🍓", time: "3 min",
      ing: [
        { n: "Yogur griego natural", e: "150 g", u: "250 g" },
        { n: "Fruta de la lista ❤️", e: "1 taza", u: "1 taza" },
        { n: "Crema de cacahuate", e: "1 cdita", u: "1 cda" },
      ],
      steps: ["Cena ligera a propósito: hoy hubo alitas. 🍗"],
      nutri: { e: "~280 kcal · 18 g proteína", u: "~430 kcal · 27 g proteína" },
    },
    "kefir-fruta": {
      t: "Kefir con fruta y avena tostada", emoji: "🥛", time: "5 min",
      ing: [
        { n: "Kefir casero", e: "250 ml", u: "350 ml" },
        { n: "Fruta picada", e: "1 taza", u: "1 taza" },
        { n: "Avena tostada", e: "2 cdas", u: "3 cdas" },
      ],
      steps: ["Cena mini: mañana empieza semana nueva.", "Tostar la avena 2 min en sartén seco."],
      nutri: { e: "~270 kcal · 12 g proteína", u: "~390 kcal · 17 g proteína" },
    },
  },

  weeks: [
    {
      id: "s1",
      label: "Semana 1",
      dates: "6 – 12 de julio, 2026",
      snack: "Snack diario permitido (~120 kcal): fruta de la lista ❤️ + café, o 100 g de yogur griego, o pepino/zanahoria con limón y chile en polvo.",
      rules: [
        "Proteína primero: en cada plato, empezar por la proteína.",
        "Aceite medido: 1 cdita por persona por guiso. Sartén antiadherente.",
        "Bebidas sin calorías: agua, café solo o con chorrito de leche, mineral con limón.",
        "Se pesan solo dos cosas: proteína y pasta/arroz (en seco).",
        "El pan dulce del sábado ya está contado. Es plan, no trampa.",
      ],
      prep: {
        title: "Prep del domingo (60–90 min, una sola vez)",
        items: [
          "Cocer 500 g de lentejas (2 comidas + 1 cena)",
          "Hornear 700 g de lomo de cerdo con ajo y mostaza (2 comidas)",
          "Cocer 2 tazas de arroz y refrigerar en porciones",
          "Salsa base: licuar jitomate + cebolla + ajo → frasco al refri (3 recetas)",
          "Lavar y picar: zanahoria, pepino, espinaca, champiñones",
          "Congelar fruta picada (fresa, mango, plátano) para licuados",
        ],
      },
      days: [
        { name: "Lunes",     desayuno: "licuado-fresa",  comida: "pasta-atun",       cena: "quesadillas" },
        { name: "Martes",    desayuno: "bowl-yogur",     comida: "lomo-camote",      cena: "tostadas-atun" },
        { name: "Miércoles", desayuno: "hotcakes-avena", comida: "lentejas-guisadas", cena: "sandwich-pavo" },
        { name: "Jueves",    desayuno: "molletes",       comida: "salteado-res",     cena: "crema-lentejas" },
        { name: "Viernes",   desayuno: "licuado-mango",  comida: "alitas",           cena: "yogur-fruta-pb" },
        { name: "Sábado",    desayuno: "pan-dulce",      comida: "camarones-ajo",    cena: "quesadillas" },
        { name: "Domingo",   desayuno: "hotcakes-avena", comida: "tacos-lomo",       cena: "kefir-fruta" },
      ],
      shopping: [
        { cat: "Proteínas 💪", items: [
          { n: "Lomo de cerdo", q: "700 g" },
          { n: "Alitas de pollo", q: "450 g" },
          { n: "Bistec de res", q: "350 g" },
          { n: "Camarón pelado", q: "300 g" },
          { n: "Atún en lata", q: "4 latas" },
          { n: "Huevo", q: "1 docena" },
          { n: "Queso panela", q: "200 g" },
          { n: "Jamón de pavo", q: "250 g" },
          { n: "Yogur griego natural", q: "1 kg" },
          { n: "Lentejas secas", q: "500 g" },
          { n: "Frijoles", q: "1 lata o 250 g" },
        ]},
        { cat: "Verduras 🥕", items: [
          { n: "Jitomate", q: "1 kg" },
          { n: "Cebolla", q: "2 piezas" },
          { n: "Zanahoria", q: "500 g" },
          { n: "Espinaca", q: "1 manojo" },
          { n: "Champiñones", q: "400 g" },
          { n: "Pepino", q: "3 piezas" },
          { n: "Ejotes", q: "200 g" },
          { n: "Brócoli", q: "1 chico" },
          { n: "Aguacate", q: "2 piezas" },
          { n: "Nopales", q: "4 pencas" },
          { n: "Ajo", q: "1 cabeza" },
          { n: "Limones", q: "½ kg" },
          { n: "Lechuga", q: "1 pieza" },
        ]},
        { cat: "Carbohidratos 🌾", items: [
          { n: "Pasta", q: "1 paquete" },
          { n: "Arroz", q: "1 kg" },
          { n: "Avena", q: "500 g" },
          { n: "Tortillas de maíz", q: "1 kg" },
          { n: "Pan integral", q: "1 paquete" },
          { n: "Tostadas horneadas", q: "1 paquete" },
          { n: "Camote", q: "3 piezas" },
          { n: "Papa", q: "4 piezas" },
        ]},
        { cat: "Frutas 🍓", items: [
          { n: "Fresas", q: "500 g" },
          { n: "Mango", q: "2 piezas" },
          { n: "Plátano", q: "6 piezas" },
          { n: "Manzana", q: "4 piezas" },
          { n: "Papaya o melón", q: "1 pieza" },
        ]},
        { cat: "Despensa 🧂", items: [
          { n: "Salsa de soya", q: "1 botella" },
          { n: "Mostaza", q: "1 frasco" },
          { n: "Crema de cacahuate", q: "1 frasco" },
          { n: "Polvo para hornear", q: "1 lata chica" },
          { n: "Canela molida", q: "1 sobre" },
          { n: "Comino", q: "1 sobre" },
          { n: "Ajo en polvo", q: "1 sobre" },
        ]},
        { cat: "El gusto del sábado 🥐", items: [
          { n: "Pan dulce", q: "2 piezas" },
        ]},
      ],
    },
  ],
};
