// MichiMenú — datos semanales. Maple genera una semana nueva cada semana y
// la agrega al FINAL de `weeks`; la app muestra la última. No borrar semanas
// pasadas: son el archivo ("reusar semana 3" en domingos flojos).
// Regla de porciones: e = ella (~1300 kcal/día) · u = tú (~1.5×).

const MICHI_DATA = {
  recipes: {
    "licuado-fresa": {
      t: "Licuado de kefir con fresa", emoji: "🥤", time: "5 min",
      ing: [
        { n: "Kefir casero", e: "250 ml", u: "350 ml" },
        { n: "Yogur griego natural", e: "100 g", u: "100 g" },
        { n: "Fresa congelada", e: "1 taza", u: "1 taza" },
        { n: "Avena", e: "3 cdas", u: "4 cdas" },
        { n: "Crema de cacahuate", e: "1 cdita", u: "1 cda" },
      ],
      steps: ["Todo a la licuadora.", "Licuar 30–40 segundos hasta quedar cremoso.", "Si está muy espeso, un chorrito de agua fría."],
      nutri: { e: "~350 kcal · 25 g proteína", u: "~520 kcal · 33 g proteína" },
    },
    "licuado-mango": {
      t: "Licuado de kefir con mango", emoji: "🥭", time: "5 min",
      ing: [
        { n: "Kefir casero", e: "250 ml", u: "350 ml" },
        { n: "Yogur griego natural", e: "100 g", u: "100 g" },
        { n: "Mango congelado", e: "1 taza", u: "1 taza" },
        { n: "Avena", e: "3 cdas", u: "4 cdas" },
      ],
      steps: ["Todo a la licuadora, 30–40 segundos.", "Canela encima si se antoja."],
      nutri: { e: "~340 kcal · 24 g proteína", u: "~480 kcal · 31 g proteína" },
    },
    "bowl-yogur": {
      t: "Bowl de yogur griego con manzana", emoji: "🍎", time: "5 min",
      ing: [
        { n: "Yogur griego natural", e: "200 g", u: "300 g" },
        { n: "Manzana picada", e: "1 pieza", u: "1 pieza" },
        { n: "Avena tostada en sartén seco", e: "2 cdas", u: "3 cdas" },
        { n: "Canela", e: "al gusto", u: "al gusto" },
      ],
      steps: ["Tostar la avena 2 min en sartén seco (huele a galleta).", "Armar el bowl: yogur, manzana, avena, canela."],
      nutri: { e: "~330 kcal · 22 g proteína", u: "~470 kcal · 31 g proteína" },
    },
    "hotcakes-avena": {
      t: "Hotcakes de avena (huevo escondido)", emoji: "🥞", time: "15 min",
      combined: true,
      ing: [
        { n: "Huevo", e: "3 piezas", u: "3 piezas" },
        { n: "Avena", e: "1¼ tazas", u: "1¼ tazas" },
        { n: "Plátano", e: "1 pieza", u: "1 pieza" },
        { n: "Polvo para hornear", e: "1 cdita", u: "1 cdita" },
        { n: "Canela", e: "al gusto", u: "al gusto" },
        { n: "Fresas para acompañar", e: "2 tazas", u: "2 tazas" },
      ],
      steps: ["Licuar huevo + avena + plátano + polvo + canela (una sola masa para los dos).", "Sartén antiadherente sin aceite, fuego medio.", "Salen ~6 medianos; voltear cuando burbujeen.", "El huevo es invisible — textura de hotcake normal. 😼"],
      split: {
        ella: "2 hotcakes + 1 taza de fresas",
        tu: "el resto (~4 hotcakes) + 1 taza de fresas",
        nota: "La masa es una sola; se reparte al servir — ella 2, tú el resto. Ya no hay que adivinar cuántos huevos son de quién.",
      },
      nutri: { e: "~350 kcal · 17 g proteína", u: "~520 kcal · 28 g proteína" },
    },
    "molletes": {
      t: "Molletes ligeros", emoji: "🍞", time: "10 min",
      ing: [
        { n: "Pan integral", e: "1 pieza", u: "2 piezas" },
        { n: "Frijoles machacados", e: "3 cdas", u: "5 cdas" },
        { n: "Queso panela rallado", e: "40 g", u: "60 g" },
        { n: "Pico de gallo (jitomate, poquita cebolla, limón)", e: "libre", u: "libre" },
      ],
      steps: ["Untar frijoles al pan, panela encima.", "Gratinar en sartén tapado u horno 5 min.", "Pico de gallo encima al servir."],
      nutri: { e: "~340 kcal · 22 g proteína", u: "~560 kcal · 35 g proteína" },
    },
    "pan-dulce": {
      t: "Pan dulce + café ☕ (el gusto de la semana)", emoji: "🥐", time: "0 min",
      ing: [
        { n: "Pan dulce favorito", e: "1 pieza", u: "1 pieza" },
        { n: "Café (solo o con chorrito de leche)", e: "1 taza", u: "1 taza" },
        { n: "Yogur griego (la proteína del día no se negocia)", e: "100 g", u: "100 g" },
      ],
      steps: ["Disfrutar sin culpa: ya está contado en la semana.", "El yogur va antes o después, como gusten."],
      nutri: { e: "~420 kcal · 14 g proteína", u: "~420 kcal · 14 g proteína" },
    },
    "pasta-atun": {
      t: "Pasta al jitomate con atún", emoji: "🍝", time: "20 min",
      ing: [
        { n: "Pasta (pesada en seco)", e: "60 g", u: "90 g" },
        { n: "Atún en lata, drenado", e: "1 lata", u: "1 lata" },
        { n: "Salsa base de jitomate (del domingo)", e: "1 taza", u: "1 taza" },
        { n: "Espinaca", e: "1 puño", u: "1 puño" },
        { n: "Queso rallado", e: "1 cda", u: "1 cda" },
      ],
      steps: ["Hervir la pasta.", "Calentar la salsa base; fundir la espinaca dentro.", "Agregar el atún, mezclar con la pasta.", "Queso espolvoreado. Sabe a Italia. 🇮🇹"],
      nutri: { e: "~490 kcal · 38 g proteína", u: "~640 kcal · 45 g proteína" },
    },
    "lomo-camote": {
      t: "Lomo de cerdo con puré de camote", emoji: "🍖", time: "15 min (lomo del domingo)",
      ing: [
        { n: "Lomo de cerdo horneado", e: "130 g", u: "200 g" },
        { n: "Camote (para el puré)", e: "1 chico", u: "1 mediano" },
        { n: "Pepino y jitomate en ensalada", e: "libre", u: "libre" },
        { n: "Limón y sal para la ensalada", e: "al gusto", u: "al gusto" },
      ],
      steps: ["Camote al micro 5–6 min, machacar con sal y tantita canela.", "Rebanar y calentar el lomo.", "Ensalada al lado."],
      nutri: { e: "~480 kcal · 38 g proteína", u: "~680 kcal · 55 g proteína" },
    },
    "lentejas-guisadas": {
      t: "Lentejas guisadas con arroz", emoji: "🍲", time: "15 min (lentejas del domingo)",
      ing: [
        { n: "Lentejas cocidas", e: "1 taza", u: "1½ tazas" },
        { n: "Zanahoria picada", e: "½ taza", u: "½ taza" },
        { n: "Espinaca", e: "1 puño", u: "1 puño" },
        { n: "Arroz cocido (del domingo)", e: "¾ taza", u: "1 taza" },
        { n: "Queso panela desmoronado", e: "40 g", u: "60 g" },
      ],
      steps: ["Guisar lentejas con la zanahoria y un cucharón de salsa base.", "Fundir la espinaca al final.", "Servir sobre el arroz, panela encima."],
      nutri: { e: "~510 kcal · 33 g proteína", u: "~690 kcal · 44 g proteína" },
    },
    "salteado-res": {
      t: "Salteado asiático de res", emoji: "🥢", time: "25 min",
      ing: [
        { n: "Bistec de res en tiras", e: "130 g", u: "200 g" },
        { n: "Champiñones rebanados", e: "1 taza", u: "1 taza" },
        { n: "Zanahoria en tiras", e: "½ taza", u: "½ taza" },
        { n: "Ejotes picados finos (modo escondido)", e: "½ taza", u: "½ taza" },
        { n: "Salsa de soya", e: "1½ cdas", u: "2 cdas" },
        { n: "Ajo picado", e: "1 diente", u: "1 diente" },
        { n: "Arroz cocido (del domingo)", e: "¾ taza", u: "1 taza" },
        { n: "Aceite", e: "1 cdita", u: "1 cdita" },
      ],
      steps: ["Sartén muy caliente: sellar la res 2 min, reservar.", "Saltear verduras 4–5 min con el ajo.", "Regresar la res, soya, 1 min más.", "Servir sobre el arroz."],
      nutri: { e: "~500 kcal · 36 g proteína", u: "~700 kcal · 52 g proteína" },
    },
    "alitas": {
      t: "ALITAS AL HORNO 🍗 (el plato estrella)", emoji: "🍗", time: "15 min manos + 40 min horno",
      ing: [
        { n: "Alitas de pollo", e: "5–6 piezas", u: "el resto de 450 g" },
        { n: "Polvo para hornear (el truco crujiente)", e: "1 cdita total", u: "—" },
        { n: "Sal y ajo en polvo", e: "al gusto", u: "al gusto" },
        { n: "Glaseado: soya + ajo, o mostaza + tantita miel", e: "1 cda", u: "1½ cdas" },
        { n: "Papas en gajos", e: "1 papa", u: "2 papas" },
        { n: "Zanahoria y pepino con limón", e: "libre", u: "libre" },
        { n: "Aceite (solo para las papas)", e: "½ cdita", u: "½ cdita" },
      ],
      steps: ["Secar las alitas MUY bien con papel — es el secreto.", "Revolcar en sal + ajo en polvo + polvo para hornear.", "Horno 220 °C sobre rejilla, 40–45 min, voltear a la mitad.", "Papas gajo en charola aparte, misma horneada.", "Barnizar con el glaseado a los últimos 5 min.", "Crujientes sin freír. Viernes de campeones."],
      nutri: { e: "~520 kcal · 32 g proteína", u: "~780 kcal · 48 g proteína" },
    },
    "camarones-ajo": {
      t: "Camarones al mojo de ajo", emoji: "🦐", time: "20 min",
      ing: [
        { n: "Camarón pelado", e: "130 g", u: "170 g" },
        { n: "Ajo picado", e: "2 dientes", u: "2 dientes" },
        { n: "Pasta (en seco) o arroz cocido", e: "60 g / ¾ taza", u: "90 g / 1 taza" },
        { n: "Aceite", e: "1 cdita", u: "1 cdita" },
        { n: "Limón y perejil o cilantro finito", e: "al gusto", u: "al gusto" },
        { n: "Ensalada de lechuga, jitomate y pepino", e: "libre", u: "libre" },
      ],
      steps: ["Dorar el ajo en el aceite a fuego bajo (sin quemar).", "Subir el fuego, camarones 2–3 min por lado.", "Limón encima, servir con pasta o arroz y ensalada."],
      nutri: { e: "~470 kcal · 35 g proteína", u: "~630 kcal · 45 g proteína" },
    },
    "tacos-lomo": {
      t: "Tacos de lomo con guacamole", emoji: "🌮", time: "15 min (lomo del domingo)",
      ing: [
        { n: "Lomo de cerdo horneado, deshebrado", e: "130 g", u: "200 g" },
        { n: "Tortillas de maíz", e: "2 piezas", u: "4 piezas" },
        { n: "Aguacate (guacamole simple)", e: "½ pieza", u: "½ pieza" },
        { n: "Nopales asados", e: "1–2 pencas", u: "1–2 pencas" },
        { n: "Limón y sal", e: "al gusto", u: "al gusto" },
      ],
      steps: ["Asar nopales en sartén o comal.", "Calentar el lomo deshebrado con un cucharón de salsa base.", "Guacamole: aguacate + limón + sal.", "Armar tacos y presumirlos."],
      nutri: { e: "~500 kcal · 37 g proteína", u: "~740 kcal · 56 g proteína" },
    },
    "quesadillas": {
      t: "Quesadillas de panela con champiñones", emoji: "🫓", time: "10 min",
      ing: [
        { n: "Tortillas de maíz", e: "2 piezas", u: "3 piezas" },
        { n: "Queso panela", e: "50 g", u: "80 g" },
        { n: "Champiñones salteados", e: "½ taza", u: "¾ taza" },
        { n: "Salsa base o pico de gallo", e: "al gusto", u: "al gusto" },
      ],
      steps: ["Saltear champiñones en sartén seco con sal.", "Armar quesadillas, dorar en comal hasta fundir."],
      nutri: { e: "~300 kcal · 19 g proteína", u: "~450 kcal · 29 g proteína" },
    },
    "tostadas-atun": {
      t: "Tostadas de atún", emoji: "🌊", time: "10 min",
      ing: [
        { n: "Tostadas horneadas", e: "2 piezas", u: "3 piezas" },
        { n: "Atún en lata, drenado", e: "1 lata", u: "1 lata" },
        { n: "Yogur griego (en vez de mayonesa)", e: "2 cdas", u: "2 cdas" },
        { n: "Jitomate picado y limón", e: "libre", u: "libre" },
      ],
      steps: ["Mezclar atún + yogur + jitomate + limón + sal.", "Montar sobre las tostadas al momento (que no se aguaden)."],
      nutri: { e: "~290 kcal · 28 g proteína", u: "~380 kcal · 34 g proteína" },
    },
    "sandwich-pavo": {
      t: "Sándwich de pavo y panela", emoji: "🥪", time: "5 min",
      ing: [
        { n: "Pan integral", e: "2 rebanadas", u: "2 rebanadas" },
        { n: "Jamón de pavo", e: "3 rebanadas", u: "4 rebanadas" },
        { n: "Queso panela", e: "30 g", u: "50 g" },
        { n: "Jitomate, lechuga, mostaza", e: "libre", u: "libre" },
      ],
      steps: ["Armar. La mostaza es gratis en calorías — generosos."],
      nutri: { e: "~310 kcal · 24 g proteína", u: "~400 kcal · 32 g proteína" },
    },
    "crema-lentejas": {
      t: "Crema de lentejas (brócoli escondido)", emoji: "🍵", time: "15 min",
      ing: [
        { n: "Lentejas cocidas (del domingo)", e: "1 taza", u: "1¼ tazas" },
        { n: "Salsa base de jitomate", e: "1 taza", u: "1 taza" },
        { n: "Brócoli", e: "2–3 flores", u: "2–3 flores" },
        { n: "Comino y sal", e: "al gusto", u: "al gusto" },
        { n: "Tortilla de maíz", e: "1 pieza", u: "2 piezas" },
      ],
      steps: ["Hervir todo junto 10 min con un poco de agua.", "Licuar TODO hasta quedar cremoso.", "Nadie detecta el brócoli. Palabra de michi. 😼"],
      nutri: { e: "~320 kcal · 20 g proteína", u: "~430 kcal · 27 g proteína" },
    },
    "yogur-fruta-pb": {
      t: "Yogur griego con fruta y cacahuate", emoji: "🍓", time: "3 min",
      ing: [
        { n: "Yogur griego natural", e: "150 g", u: "250 g" },
        { n: "Fruta de la lista ❤️", e: "1 taza", u: "1 taza" },
        { n: "Crema de cacahuate", e: "1 cdita", u: "1 cda" },
      ],
      steps: ["Cena ligera a propósito: hoy hubo alitas. 🍗"],
      nutri: { e: "~280 kcal · 18 g proteína", u: "~430 kcal · 27 g proteína" },
    },
    "kefir-fruta": {
      t: "Kefir con fruta y avena tostada", emoji: "🥛", time: "5 min",
      ing: [
        { n: "Kefir casero", e: "250 ml", u: "350 ml" },
        { n: "Fruta picada", e: "1 taza", u: "1 taza" },
        { n: "Avena tostada", e: "2 cdas", u: "3 cdas" },
      ],
      steps: ["Cena mini: mañana empieza semana nueva.", "Tostar la avena 2 min en sartén seco."],
      nutri: { e: "~270 kcal · 12 g proteína", u: "~390 kcal · 17 g proteína" },
    },
    "caldo-pollo": {
      t: "Caldo de pollo (el que pidió la michi 🐱)", emoji: "🍜", time: "10 min (del prep del sábado)",
      ing: [
        { n: "Pollo cocido (del caldo del sábado)", e: "130 g", u: "200 g" },
        { n: "Caldo con zanahoria, papa y calabacita", e: "1 plato hondo", u: "1 plato hondo" },
        { n: "Arroz cocido", e: "¼ taza", u: "⅓ taza" },
        { n: "Aguacate", e: "¼ pieza", u: "¼ pieza" },
        { n: "Limón, cilantro finito y tortilla", e: "al gusto", u: "al gusto" },
      ],
      steps: ["Calentar el caldo con sus verduras y el pollo.", "Servir con el arroz, aguacate y limón.", "Tortilla al lado. Reconforta y llena sin pesar."],
      nutri: { e: "~430 kcal · 35 g proteína", u: "~600 kcal · 50 g proteína" },
    },
    "salmon-camote": {
      t: "Salmón al horno con camote", emoji: "🐟", time: "25 min",
      ing: [
        { n: "Salmón", e: "130 g", u: "180 g" },
        { n: "Camote al horno", e: "1 chico", u: "1 mediano" },
        { n: "Espinaca salteada con ajo", e: "1 puño", u: "1 puño" },
        { n: "Ajo, limón, soya", e: "al gusto", u: "al gusto" },
        { n: "Aceite", e: "1 cdita", u: "1 cdita" },
      ],
      steps: ["Salmón con ajo, limón y un toque de soya, horno 200 °C 12–15 min.", "Camote al horno o micro, machacar con sal.", "Espinaca salteada 2 min. Emplatar."],
      nutri: { e: "~470 kcal · 34 g proteína", u: "~650 kcal · 44 g proteína" },
    },
    "garbanzos-guisados": {
      t: "Garbanzos guisados con arroz", emoji: "🫘", time: "15 min",
      ing: [
        { n: "Garbanzos cocidos", e: "1 taza", u: "1½ tazas" },
        { n: "Salsa base de jitomate", e: "1 taza", u: "1 taza" },
        { n: "Espinaca", e: "1 puño", u: "1 puño" },
        { n: "Arroz cocido", e: "¾ taza", u: "1 taza" },
        { n: "Queso panela desmoronado", e: "40 g", u: "60 g" },
      ],
      steps: ["Guisar los garbanzos con la salsa base y comino.", "Fundir la espinaca al final.", "Servir sobre el arroz, panela encima."],
      nutri: { e: "~500 kcal · 24 g proteína", u: "~680 kcal · 32 g proteína" },
    },
    "chilaquiles-ligeros": {
      t: "Chilaquiles verdes ligeros con pollo", emoji: "🍳", time: "15 min",
      ing: [
        { n: "Tortilla de maíz horneada en totopos", e: "2 piezas", u: "3 piezas" },
        { n: "Salsa verde ligera (tomate verde + chile suave)", e: "½ taza", u: "¾ taza" },
        { n: "Pollo deshebrado (del prep)", e: "60 g", u: "90 g" },
        { n: "Huevo (escondido, revuelto encima)", e: "1 pieza", u: "1 pieza" },
        { n: "Yogur griego (en vez de crema) y panela", e: "1 cda / 20 g", u: "2 cdas / 30 g" },
      ],
      steps: ["Hornear los totopos hasta dorar (sin freír).", "Calentar la salsa verde y bañar los totopos al momento.", "Encima: pollo, huevo revuelto, cucharada de yogur y panela.", "Desayuno fuerte para quien despierta con hambre."],
      nutri: { e: "~400 kcal · 30 g proteína", u: "~560 kcal · 40 g proteína" },
    },
    "pasta-champinones-pollo": {
      t: "Pasta cremosa de champiñones con pollo", emoji: "🍝", time: "20 min",
      ing: [
        { n: "Pasta (pesada en seco)", e: "60 g", u: "90 g" },
        { n: "Pollo deshebrado (del prep)", e: "80 g", u: "120 g" },
        { n: "Champiñones rebanados", e: "1 taza", u: "1 taza" },
        { n: "Yogur griego (la crema secreta)", e: "3 cdas", u: "4 cdas" },
        { n: "Ajo, espinaca, queso rallado", e: "al gusto", u: "al gusto" },
        { n: "Aceite", e: "1 cdita", u: "1 cdita" },
      ],
      steps: ["Hervir la pasta.", "Saltear champiñones con ajo; agregar pollo y espinaca.", "Fuera del fuego, integrar el yogur (que no hierva = no se corta).", "Mezclar con la pasta, queso encima. Cremosa sin crema."],
      nutri: { e: "~500 kcal · 37 g proteína", u: "~700 kcal · 50 g proteína" },
    },
    "tinga-pollo": {
      t: "Tinga de pollo light en tostadas", emoji: "🌶️", time: "15 min (pollo del prep)",
      ing: [
        { n: "Pollo deshebrado (del prep)", e: "120 g", u: "180 g" },
        { n: "Salsa base + 1 chile chipotle (suave)", e: "¾ taza", u: "¾ taza" },
        { n: "Tostadas horneadas", e: "2 piezas", u: "3 piezas" },
        { n: "Frijoles machacados", e: "3 cdas", u: "4 cdas" },
        { n: "Aguacate, lechuga, panela", e: "al gusto", u: "al gusto" },
      ],
      steps: ["Guisar el pollo con la salsa base y el chipotle 5 min (picor suave).", "Untar frijol a la tostada, tinga encima.", "Lechuga, aguacate y panela. Guardar tinga extra para los tacos del domingo."],
      nutri: { e: "~470 kcal · 34 g proteína", u: "~660 kcal · 46 g proteína" },
    },
    "albondigas-res": {
      t: "Albóndigas de res en salsa", emoji: "🍖", time: "30 min",
      ing: [
        { n: "Carne molida de res", e: "130 g", u: "200 g" },
        { n: "Salsa base de jitomate", e: "1 taza", u: "1 taza" },
        { n: "Zanahoria rallada (escondida en la albóndiga)", e: "2 cdas", u: "3 cdas" },
        { n: "Avena molida (para ligar, en vez de pan)", e: "1 cda", u: "2 cdas" },
        { n: "Puré de papa ligero (con yogur)", e: "1 papa", u: "1 papa grande" },
      ],
      steps: ["Mezclar carne + zanahoria + avena + ajo + sal, bolear.", "Cocer en la salsa base a fuego medio 20 min.", "Puré: papa cocida machacada con 1 cda de yogur y sal.", "La zanahoria escondida da jugosidad. 😼"],
      nutri: { e: "~500 kcal · 33 g proteína", u: "~720 kcal · 48 g proteína" },
    },
    "ensalada-garbanzo-atun": {
      t: "Ensalada de garbanzo y atún", emoji: "🥗", time: "8 min",
      ing: [
        { n: "Garbanzos cocidos", e: "½ taza", u: "¾ taza" },
        { n: "Atún en lata, drenado", e: "1 lata", u: "1 lata" },
        { n: "Jitomate, pepino, espinaca", e: "libre", u: "libre" },
        { n: "Limón, mostaza y aceite", e: "1 cdita aceite", u: "1 cdita aceite" },
      ],
      steps: ["Revolver todo con limón, mostaza y tantita sal.", "Cena de proteína, rápida y fresca."],
      nutri: { e: "~300 kcal · 26 g proteína", u: "~400 kcal · 33 g proteína" },
    },
    "tostada-frijol-aguacate": {
      t: "Tostadas de frijol y aguacate", emoji: "🥑", time: "5 min",
      ing: [
        { n: "Tostadas horneadas", e: "2 piezas", u: "3 piezas" },
        { n: "Frijoles machacados", e: "4 cdas", u: "6 cdas" },
        { n: "Aguacate", e: "½ pieza", u: "½ pieza" },
        { n: "Queso panela, jitomate, limón", e: "al gusto", u: "al gusto" },
      ],
      steps: ["Untar frijol, aguacate en rebanadas, panela y jitomate.", "Limón y sal. Cena de ensamble en 5 minutos."],
      nutri: { e: "~320 kcal · 15 g proteína", u: "~470 kcal · 22 g proteína" },
    },
    "cottage-fruta": {
      t: "Cottage con fruta y avena", emoji: "🍑", time: "3 min",
      ing: [
        { n: "Queso cottage", e: "150 g", u: "220 g" },
        { n: "Fruta de la lista ❤️", e: "1 taza", u: "1 taza" },
        { n: "Avena tostada y canela", e: "2 cdas", u: "3 cdas" },
      ],
      steps: ["Armar el bowl. Cottage = mucha proteína, pocas calorías."],
      nutri: { e: "~250 kcal · 22 g proteína", u: "~360 kcal · 30 g proteína" },
    },
    "tacos-tinga": {
      t: "Tacos de tinga (sobró del viernes)", emoji: "🌮", time: "8 min",
      ing: [
        { n: "Tinga de pollo (sobrante)", e: "120 g", u: "180 g" },
        { n: "Tortillas de maíz", e: "2 piezas", u: "4 piezas" },
        { n: "Aguacate, cebolla morada, limón", e: "al gusto", u: "al gusto" },
      ],
      steps: ["Calentar la tinga.", "Tacos con aguacate y limón. Cierre de semana sin cocinar de más."],
      nutri: { e: "~440 kcal · 32 g proteína", u: "~700 kcal · 48 g proteína" },
    },
    "prep-caldo": {
      t: "Caldo de pollo (base del martes)", emoji: "🍜", time: "10 min manos + 40–50 min",
      ing: [
        { n: "Pollo con hueso (muslo, pierna, alita)", e: "1.2–1.5 kg", u: "1.2–1.5 kg" },
        { n: "Zanahoria en rodajas gruesas de ~3 cm", e: "2 piezas", u: "2 piezas" },
        { n: "Papa en cubos grandes de ~4 cm", e: "1–2 piezas", u: "1–2 piezas" },
        { n: "Calabacita en medias lunas de ~2 cm (va al final)", e: "1–2 piezas", u: "1–2 piezas" },
        { n: "Apio en trozos de ~5 cm", e: "1–2 tallos", u: "1–2 tallos" },
        { n: "Cebolla en trozo grande + ajo machacado", e: "½ + 2–3 dientes", u: "½ + 2–3 dientes" },
        { n: "Sal, laurel (1–2 hojas), pimienta en grano (6–8), consomé opcional", e: "al gusto", u: "al gusto" },
      ],
      steps: [
        "Pon el pollo en AGUA FRÍA desde el inicio, que lo cubra bien.",
        "Agrega zanahoria, papa, apio, cebolla, ajo, laurel, pimienta y sal.",
        "Sube a hervor y ESPUMA la nata gris de la superficie (caldo limpio).",
        "Baja el fuego, tapa entreabierta, 40–50 min.",
        "Mete la calabacita solo los últimos 15 min (si no, se hace puré).",
        "Saca el pollo: deshebra la mayoría para los otros platos, deja unos trozos en el caldo.",
        "Servir el martes: caldo + verdura + pollo + arroz; aparte aguacate, limón, cebolla, cilantro. El chile, aparte para ti.",
      ],
    },
    "prep-salsa-base": {
      t: "Salsa base roja (comodín de 4 platos)", emoji: "🍅", time: "15 min",
      ing: [
        { n: "Jitomate maduro (entero)", e: "6 piezas", u: "6 piezas" },
        { n: "Cebolla en cuartos", e: "½ pieza", u: "½ pieza" },
        { n: "Ajo pelado", e: "2 dientes", u: "2 dientes" },
        { n: "Sal + 1 pizca de comino (orégano opcional)", e: "al gusto", u: "al gusto" },
      ],
      steps: [
        "Asa en comal jitomate, cebolla y ajo hasta que tengan manchas negras (más sabor); o hiérvelos 10 min.",
        "Licua con sal y comino.",
        "Opcional: sofríe la salsa 5 min en 1 cdita de aceite para concentrar el sabor.",
        "Frasco al refri. Es la base de garbanzos, tinga, albóndigas y pasta.",
      ],
    },
    "prep-salsa-verde": {
      t: "Salsa verde ligera (chilaquiles y tinga)", emoji: "🌶️", time: "12 min",
      ing: [
        { n: "Tomate verde pelado y enjuagado", e: "8–10 piezas", u: "8–10 piezas" },
        { n: "Chile suave SIN semillas (jalapeño o serrano chico)", e: "1 pieza", u: "1 pieza" },
        { n: "Ajo + ¼ de cebolla cruda", e: "1 diente", u: "1 diente" },
        { n: "Cilantro (poquito) y sal", e: "al gusto", u: "al gusto" },
      ],
      steps: [
        "Hierve tomate verde + chile 8 min, hasta que cambien de color.",
        "Licua con el ajo, la cebolla CRUDA, cilantro y sal.",
        "Frasco aparte. Sin semillas = picor suave para que le guste a ella.",
      ],
    },
    "prep-arroz": {
      t: "Arroz blanco", emoji: "🍚", time: "5 min manos + 15 min",
      ing: [
        { n: "Arroz enjuagado", e: "1 taza", u: "1 taza" },
        { n: "Agua caliente o caldo del pollo", e: "2 tazas", u: "2 tazas" },
        { n: "Cebolla, ajo, ½ cdita de aceite, sal", e: "½ + 1 diente", u: "½ + 1 diente" },
      ],
      steps: [
        "Dora el arroz 2 min con el aceite, el ajo y la cebolla.",
        "Agrega el líquido CALIENTE + sal.",
        "Tapa 15 min a fuego bajo; apaga y reposa 5 min sin destapar.",
        "Esponja con un tenedor.",
      ],
    },
    "prep-garbanzos": {
      t: "Garbanzos (rinden 2 platos)", emoji: "🫘", time: "5 min (de lata)",
      ing: [
        { n: "Garbanzos de lata (o secos remojados)", e: "2 latas", u: "2 latas" },
        { n: "Si son secos: ajo, ¼ cebolla, 1 laurel, sal", e: "al gusto", u: "al gusto" },
      ],
      steps: [
        "De lata: enjuaga MUY bien (les quita el sabor a lata).",
        "Secos: cuece con ajo, cebolla, laurel y sal ~40 min (o exprés en olla de presión).",
        "Táper al refri. Rinden guisados (miércoles) + ensalada (lunes).",
      ],
    },
    "prep-mise": {
      t: "Picar la semana (mise en place)", emoji: "🔪", time: "15 min",
      ing: [
        { n: "Zanahoria: mitad en juliana (tiras finas) + mitad en cubo chico", e: "—", u: "—" },
        { n: "Espinaca: lavada y bien seca, hoja entera", e: "—", u: "—" },
        { n: "Champiñones: rebanados de ~½ cm", e: "—", u: "—" },
        { n: "Cebolla morada: fileteada fina, en agua con limón", e: "—", u: "—" },
        { n: "Pepino y lechuga: NO picar hoy (se aguadan)", e: "—", u: "—" },
      ],
      steps: [
        "Corta cada verdura a su tamaño y guárdala en su táper.",
        "Mete UNA toalla de papel en cada táper: absorbe humedad y dura fresca toda la semana.",
        "El pepino y la lechuga se cortan al momento de usarlos.",
      ],
    },

    /* ---------- ollas por lote (semana 3: cocina 1 vez, come 2 días) ---------- */
    "guiso-pollo-mexicana": {
      t: "Guiso de pollo a la mexicana (olla para 2 días)", emoji: "🍗", time: "35 min (una sola vez)",
      combined: true,
      ing: [
        { n: "Pechuga y muslo de pollo en cubos", e: "600 g", u: "600 g" },
        { n: "Jitomate picado", e: "4 piezas", u: "4 piezas" },
        { n: "Cebolla picada", e: "1 pieza", u: "1 pieza" },
        { n: "Chile poblano en rajas (suave)", e: "1 pieza", u: "1 pieza" },
        { n: "Calabacita en cubos", e: "2 piezas", u: "2 piezas" },
        { n: "Papa en cubos", e: "2 piezas", u: "2 piezas" },
        { n: "Ajo", e: "2 dientes", u: "2 dientes" },
        { n: "Aceite", e: "1 cda (toda la olla)", u: "1 cda (toda la olla)" },
        { n: "Arroz cocido para acompañar", e: "al servir", u: "al servir" },
      ],
      steps: [
        "🔁 Rinde 4 porciones = los dos, 2 días (lun-mar). Cantidades para toda la olla, no por plato.",
        "Sofríe cebolla y ajo con 1 cda de aceite. Dora el pollo.",
        "Suma jitomate y poblano, 5 min hasta que suelte jugo.",
        "Papa y calabacita + un chorrito de agua; tapa 15 min hasta que estén suaves. Sal al gusto.",
        "Acompaña con arroz o tortillas.",
      ],
      split: {
        ella: "1 plato (~1½ tazas) + ¾ taza de arroz",
        tu: "el resto, porción más grande + 1 taza de arroz",
        nota: "Apenas se entibie, reparte en 4 tápers: 2 de ella (más chicos) + 2 tuyos (más grandes), etiquétalos y al refri. Cada día agarras el tuyo — ya no hay que adivinar. 🥡",
      },
      nutri: { e: "~470 kcal · 40 g proteína", u: "~660 kcal · 55 g proteína" },
    },
    "chili-res-frijol": {
      t: "Chili de res con frijol (olla para 2 días)", emoji: "🌶️", time: "35 min (una sola vez)",
      combined: true,
      ing: [
        { n: "Carne molida de res magra", e: "500 g", u: "500 g" },
        { n: "Frijol cocido (o de lata, drenado)", e: "2 tazas", u: "2 tazas" },
        { n: "Jitomate picado", e: "3 piezas", u: "3 piezas" },
        { n: "Cebolla y pimiento picados", e: "1 c/u", u: "1 c/u" },
        { n: "Zanahoria rallada (escondida)", e: "1 pieza", u: "1 pieza" },
        { n: "Comino y chile en polvo", e: "1 cdita c/u", u: "1 cdita c/u" },
        { n: "Ajo", e: "2 dientes", u: "2 dientes" },
        { n: "Aceite", e: "1 cda (toda la olla)", u: "1 cda (toda la olla)" },
      ],
      steps: [
        "🔁 Rinde 4 porciones = los dos, 2 días (mié-jue).",
        "Dora la carne sin aceite; escurre la grasa que suelte.",
        "Sofríe cebolla, pimiento, ajo y zanahoria con 1 cda de aceite.",
        "Regresa la carne + jitomate + especias, 5 min.",
        "Frijol y ½ taza de agua, 12–15 min a fuego suave hasta espesar.",
      ],
      split: {
        ella: "1 plato hondo (~1¼ tazas) + tortilla o arroz medido",
        tu: "el resto, porción más grande",
        nota: "Reparte en 4 tápers en cuanto se entibie: 2 de ella + 2 tuyos, etiquetados. 🥡",
      },
      nutri: { e: "~480 kcal · 34 g proteína", u: "~680 kcal · 48 g proteína" },
    },
    "cerdo-salsa-verde": {
      t: "Cerdo deshebrado en salsa verde (olla para 2 días)", emoji: "🥩", time: "45 min (una sola vez)",
      combined: true,
      ing: [
        { n: "Pierna o lomo de cerdo magro", e: "700 g", u: "700 g" },
        { n: "Tomate verde", e: "8 piezas", u: "8 piezas" },
        { n: "Chile serrano (al gusto, suave)", e: "1 pieza", u: "1 pieza" },
        { n: "Cebolla y ajo", e: "½ + 2 dientes", u: "½ + 2 dientes" },
        { n: "Cilantro", e: "unas ramas", u: "unas ramas" },
        { n: "Aceite", e: "1 cdita (toda la olla)", u: "1 cdita (toda la olla)" },
        { n: "Tortillas o arroz para acompañar", e: "al servir", u: "al servir" },
      ],
      steps: [
        "🔁 Rinde 4 porciones = los dos, 2 días (vie-sáb). Sirve como plato o en tacos.",
        "Cuece el cerdo en agua con ½ cebolla y ajo ~35 min; deshébralo. Guarda el caldito.",
        "Salsa verde: hierve tomate verde + serrano 8 min, licúa con cebolla, ajo y cilantro.",
        "Sella la salsa con 1 cdita de aceite 3 min, suma el cerdo deshebrado y un poco de su caldo, 8 min.",
        "Sal al gusto.",
      ],
      split: {
        ella: "~¾ taza de cerdo + 2 tortillas (o arroz medido) + ensalada",
        tu: "el resto, porción más grande + 3 tortillas",
        nota: "Reparte en 4 tápers: 2 de ella + 2 tuyos, etiquetados. El sábado puedes armarlo en tacos. 🥡",
      },
      nutri: { e: "~460 kcal · 42 g proteína", u: "~660 kcal · 58 g proteína" },
    },
    "pescado-veracruzana": {
      t: "Pescado a la veracruzana (del domingo)", emoji: "🐟", time: "30 min",
      combined: true,
      ing: [
        { n: "Filete de pescado blanco (tilapia/basa)", e: "1 filete", u: "1 filete grande" },
        { n: "Jitomate picado", e: "3 piezas", u: "3 piezas" },
        { n: "Cebolla en pluma", e: "½ pieza", u: "½ pieza" },
        { n: "Aceitunas y alcaparras", e: "un puño", u: "un puño" },
        { n: "Ajo", e: "2 dientes", u: "2 dientes" },
        { n: "Aceite", e: "1 cdita", u: "1 cdita" },
        { n: "Arroz para acompañar", e: "¾ taza", u: "1 taza" },
      ],
      steps: [
        "Sofríe cebolla y ajo, suma jitomate, aceitunas y alcaparras, 8 min.",
        "Acomoda los filetes en la salsa, tapa 8–10 min a fuego suave (no lo revuelvas mucho).",
        "Sirve con arroz. Es fresco del domingo — este no va a táper.",
      ],
      split: {
        ella: "1 filete + ¾ taza de arroz",
        tu: "el filete grande + 1 taza de arroz",
        nota: "Este se come recién hecho; el reparto es directo al plato (el filete de cada quien ya viene separado).",
      },
      nutri: { e: "~430 kcal · 40 g proteína", u: "~600 kcal · 52 g proteína" },
    },
  },

  weeks: [
    {
      id: "s1",
      label: "Semana 1",
      dates: "6 – 12 de julio, 2026",
      snack: "Snack diario permitido (~120 kcal): fruta de la lista ❤️ + café, o 100 g de yogur griego, o pepino/zanahoria con limón y chile en polvo.",
      rules: [
        "Proteína primero: en cada plato, empezar por la proteína.",
        "Aceite medido: 1 cdita por persona por guiso. Sartén antiadherente.",
        "Bebidas sin calorías: agua, café solo o con chorrito de leche, mineral con limón.",
        "Se pesan solo dos cosas: proteína y pasta/arroz (en seco).",
        "El pan dulce del sábado ya está contado. Es plan, no trampa.",
      ],
      prep: {
        title: "Prep del domingo (60–90 min, una sola vez)",
        items: [
          "Cocer 500 g de lentejas (2 comidas + 1 cena)",
          "Hornear 700 g de lomo de cerdo con ajo y mostaza (2 comidas)",
          "Cocer 2 tazas de arroz y refrigerar en porciones",
          "Salsa base: licuar jitomate + cebolla + ajo → frasco al refri (3 recetas)",
          "Lavar y picar: zanahoria, pepino, espinaca, champiñones",
          "Congelar fruta picada (fresa, mango, plátano) para licuados",
        ],
      },
      days: [
        { name: "Lunes",     desayuno: "licuado-fresa",  comida: "pasta-atun",       cena: "quesadillas" },
        { name: "Martes",    desayuno: "bowl-yogur",     comida: "lomo-camote",      cena: "tostadas-atun" },
        { name: "Miércoles", desayuno: "hotcakes-avena", comida: "lentejas-guisadas", cena: "sandwich-pavo" },
        { name: "Jueves",    desayuno: "molletes",       comida: "salteado-res",     cena: "crema-lentejas" },
        { name: "Viernes",   desayuno: "licuado-mango",  comida: "alitas",           cena: "yogur-fruta-pb" },
        { name: "Sábado",    desayuno: "pan-dulce",      comida: "camarones-ajo",    cena: "quesadillas" },
        { name: "Domingo",   desayuno: "hotcakes-avena", comida: "tacos-lomo",       cena: "kefir-fruta" },
      ],
      shopping: [
        { cat: "Proteínas 💪", items: [
          { n: "Lomo de cerdo", q: "700 g" },
          { n: "Alitas de pollo", q: "450 g" },
          { n: "Bistec de res", q: "350 g" },
          { n: "Camarón pelado", q: "300 g" },
          { n: "Atún en lata", q: "4 latas" },
          { n: "Huevo", q: "1 docena" },
          { n: "Queso panela", q: "200 g" },
          { n: "Jamón de pavo", q: "250 g" },
          { n: "Yogur griego natural", q: "1 kg" },
          { n: "Lentejas secas", q: "500 g" },
          { n: "Frijoles", q: "1 lata o 250 g" },
        ]},
        { cat: "Verduras 🥕", items: [
          { n: "Jitomate", q: "1 kg" },
          { n: "Cebolla", q: "2 piezas" },
          { n: "Zanahoria", q: "500 g" },
          { n: "Espinaca", q: "1 manojo" },
          { n: "Champiñones", q: "400 g" },
          { n: "Pepino", q: "3 piezas" },
          { n: "Ejotes", q: "200 g" },
          { n: "Brócoli", q: "1 chico" },
          { n: "Aguacate", q: "2 piezas" },
          { n: "Nopales", q: "4 pencas" },
          { n: "Ajo", q: "1 cabeza" },
          { n: "Limones", q: "½ kg" },
          { n: "Lechuga", q: "1 pieza" },
        ]},
        { cat: "Carbohidratos 🌾", items: [
          { n: "Pasta", q: "1 paquete" },
          { n: "Arroz", q: "1 kg" },
          { n: "Avena", q: "500 g" },
          { n: "Tortillas de maíz", q: "1 kg" },
          { n: "Pan integral", q: "1 paquete" },
          { n: "Tostadas horneadas", q: "1 paquete" },
          { n: "Camote", q: "3 piezas" },
          { n: "Papa", q: "4 piezas" },
        ]},
        { cat: "Frutas 🍓", items: [
          { n: "Fresas", q: "500 g" },
          { n: "Mango", q: "2 piezas" },
          { n: "Plátano", q: "6 piezas" },
          { n: "Manzana", q: "4 piezas" },
          { n: "Papaya o melón", q: "1 pieza" },
        ]},
        { cat: "Despensa 🧂", items: [
          { n: "Salsa de soya", q: "1 botella" },
          { n: "Mostaza", q: "1 frasco" },
          { n: "Crema de cacahuate", q: "1 frasco" },
          { n: "Polvo para hornear", q: "1 lata chica" },
          { n: "Canela molida", q: "1 sobre" },
          { n: "Comino", q: "1 sobre" },
          { n: "Ajo en polvo", q: "1 sobre" },
        ]},
        { cat: "El gusto del sábado 🥐", items: [
          { n: "Pan dulce", q: "2 piezas" },
        ]},
      ],
    },
    {
      id: "s2",
      label: "Semana 2",
      dates: "18 – 24 de julio, 2026",
      snack: "Snack diario permitido (~120 kcal): fruta de la lista ❤️ + café, o 100 g de yogur griego, o pepino/zanahoria con limón y chile en polvo.",
      rules: [
        "Proteína primero: en cada plato, empezar por la proteína.",
        "Aceite medido: 1 cdita por persona por guiso. Sartén antiadherente.",
        "Bebidas sin calorías: agua, café solo o con chorrito de leche, mineral con limón.",
        "Se pesan solo dos cosas: proteína y pasta/arroz (en seco).",
        "El pan dulce del sábado ya está contado. Es plan, no trampa.",
        "El pollo es el héroe de la semana: un solo cocido da el caldo + el pollo deshebrado de 3 platos.",
      ],
      prep: {
        title: "Prep del sábado (hoy, 75–90 min)",
        intro: "El pollo es el héroe: un solo cocido da el caldo + el deshebrado de 3 platos. Arráncalo primero y haz lo demás mientras hierve. Toca cada paso para ver receta, cortes y condimentos. 👇",
        items: [
          { t: "1. Arranca el caldo de pollo (primero)", r: "prep-caldo" },
          { t: "2. Salsa base roja", r: "prep-salsa-base" },
          { t: "3. Salsa verde ligera", r: "prep-salsa-verde" },
          { t: "4. Arroz blanco", r: "prep-arroz" },
          { t: "5. Garbanzos", r: "prep-garbanzos" },
          { t: "6. Picar la semana", r: "prep-mise" },
          "7. Fruta para licuados: pica fresa, mango y plátano en porciones de 1 taza → bolsitas al congelador.",
        ],
      },
      days: [
        { name: "Lunes",     desayuno: "licuado-fresa",       comida: "salmon-camote",           cena: "ensalada-garbanzo-atun" },
        { name: "Martes",    desayuno: "chilaquiles-ligeros", comida: "caldo-pollo",             cena: "cottage-fruta" },
        { name: "Miércoles", desayuno: "bowl-yogur",          comida: "garbanzos-guisados",      cena: "sandwich-pavo" },
        { name: "Jueves",    desayuno: "hotcakes-avena",      comida: "pasta-champinones-pollo", cena: "tostada-frijol-aguacate" },
        { name: "Viernes",   desayuno: "licuado-mango",       comida: "tinga-pollo",             cena: "yogur-fruta-pb" },
        { name: "Sábado",    desayuno: "pan-dulce",           comida: "albondigas-res",          cena: "quesadillas" },
        { name: "Domingo",   desayuno: "bowl-yogur",          comida: "tacos-tinga",             cena: "kefir-fruta" },
      ],
      shopping: [
        { cat: "Proteínas 💪", items: [
          { n: "Pollo (para caldo + deshebrar)", q: "1.2–1.5 kg" },
          { n: "Salmón", q: "2 filetes (~320 g)" },
          { n: "Carne molida de res", q: "350 g" },
          { n: "Atún en lata", q: "2 latas" },
          { n: "Garbanzos", q: "2 latas o 400 g secos" },
          { n: "Queso panela", q: "200 g" },
          { n: "Queso cottage", q: "200 g" },
          { n: "Jamón de pavo", q: "200 g" },
          { n: "Yogur griego natural", q: "1 kg" },
          { n: "Huevo", q: "1 docena" },
          { n: "Frijoles", q: "1 lata o 250 g" },
        ]},
        { cat: "Verduras 🥕", items: [
          { n: "Jitomate", q: "1 kg" },
          { n: "Tomate verde", q: "500 g" },
          { n: "Cebolla (+ 1 morada)", q: "3 piezas" },
          { n: "Zanahoria", q: "500 g" },
          { n: "Papa", q: "4 piezas" },
          { n: "Calabacita", q: "3 piezas" },
          { n: "Apio", q: "1 manojo chico" },
          { n: "Espinaca", q: "1 manojo" },
          { n: "Champiñones", q: "300 g" },
          { n: "Aguacate", q: "3 piezas" },
          { n: "Chile chipotle o jalapeño (suave)", q: "1 chico" },
          { n: "Ajo", q: "1 cabeza" },
          { n: "Limones", q: "½ kg" },
          { n: "Lechuga", q: "1 pieza" },
          { n: "Pepino", q: "2 piezas" },
        ]},
        { cat: "Carbohidratos 🌾", items: [
          { n: "Pasta", q: "1 paquete" },
          { n: "Arroz", q: "1 kg" },
          { n: "Avena", q: "500 g" },
          { n: "Tortillas de maíz", q: "1 kg" },
          { n: "Tostadas horneadas", q: "1 paquete" },
          { n: "Pan integral", q: "1 paquete" },
          { n: "Camote", q: "2 piezas" },
        ]},
        { cat: "Frutas 🍓", items: [
          { n: "Fresas", q: "500 g" },
          { n: "Mango", q: "2 piezas" },
          { n: "Plátano", q: "6 piezas" },
          { n: "Manzana", q: "4 piezas" },
          { n: "Papaya o melón", q: "1 pieza" },
        ]},
        { cat: "Despensa 🧂", items: [
          { n: "Salsa de soya", q: "si falta" },
          { n: "Mostaza", q: "si falta" },
          { n: "Crema de cacahuate", q: "si falta" },
          { n: "Comino", q: "1 sobre" },
          { n: "Canela molida", q: "si falta" },
          { n: "Chile en polvo", q: "1 sobre" },
        ]},
        { cat: "El gusto del sábado 🥐", items: [
          { n: "Pan dulce", q: "2 piezas" },
        ]},
      ],
    },
    {
      id: "s3",
      label: "Semana 3 — a su ritmo (cocina por lotes)",
      dates: "27 de julio – 2 de agosto, 2026",
      snack: "Snack diario permitido (~120 kcal): fruta de la lista ❤️ + café, o 100 g de yogur griego, o pepino/zanahoria con limón y chile en polvo.",
      rules: [
        "El cambio grande: cocinas 3 veces en la semana, no 7. Cada olla rinde 2 días para los dos (más fácil con sus horarios).",
        "Se cocina TODO junto y se reparte al final: los ingredientes son el total para los dos; la porción de ella es el ancla y lo tuyo es 'el resto' (más grande).",
        "Reparte cada olla en 4 tápers etiquetados apenas se entibie (2 de ella + 2 tuyos). Así ya no hay que adivinar qué es de quién ni volver a pesar.",
        "Se recalienta en sartén u olla con un chorrito de agua. Sabe igual o mejor al 2º día.",
        "Proteína primero; aceite medido (1 cda por olla). El pan dulce del sábado ya está contado. Es plan, no trampa.",
      ],
      prep: {
        title: "Cocina 3 veces, no 7 (cada olla, 2 días)",
        intro: "El cambio de esta semana: en vez de algo distinto cada día, haces 3 ollas y cada una rinde 2 días para los dos. Cocinas, repartes en tápers etiquetados (los de ella más chicos, los tuyos más grandes) y el resto de la semana solo recalientas. Toca cada paso para ver la receta. 👇",
        items: [
          { t: "1. Fin de semana: Guiso de pollo a la mexicana (rinde lun-mar)", r: "guiso-pollo-mexicana" },
          "2. Mismo día: cuece 2 tazas de arroz y una olla de frijol; guárdalos en porciones al refri.",
          { t: "3. Martes en la tarde: Chili de res con frijol (rinde mié-jue)", r: "chili-res-frijol" },
          { t: "4. Jueves en la tarde: Cerdo en salsa verde (rinde vie-sáb)", r: "cerdo-salsa-verde" },
          "5. Cada olla: repártela en 4 tápers apenas se entibie — 2 de ella (más chicos) + 2 tuyos (más grandes), etiquétalos. Ese es todo el chiste: ya sabes qué es de quién sin volver a pesar. 🥡",
          "6. Fruta para licuados: pica fresa y mango en porciones de 1 taza → bolsitas al congelador.",
        ],
      },
      days: [
        { name: "Lunes",     desayuno: "licuado-fresa",       comida: "guiso-pollo-mexicana", cena: "ensalada-garbanzo-atun" },
        { name: "Martes",    desayuno: "molletes",            comida: "guiso-pollo-mexicana", cena: "quesadillas" },
        { name: "Miércoles", desayuno: "bowl-yogur",          comida: "chili-res-frijol",     cena: "sandwich-pavo" },
        { name: "Jueves",    desayuno: "hotcakes-avena",      comida: "chili-res-frijol",     cena: "cottage-fruta" },
        { name: "Viernes",   desayuno: "licuado-mango",       comida: "cerdo-salsa-verde",    cena: "tostada-frijol-aguacate" },
        { name: "Sábado",    desayuno: "pan-dulce",           comida: "cerdo-salsa-verde",    cena: "quesadillas" },
        { name: "Domingo",   desayuno: "chilaquiles-ligeros", comida: "pescado-veracruzana",  cena: "kefir-fruta" },
      ],
      shopping: [
        { cat: "Proteínas 💪", items: [
          { n: "Pollo (pechuga + muslo)", q: "700 g" },
          { n: "Carne molida de res magra", q: "500 g" },
          { n: "Pierna o lomo de cerdo", q: "700 g" },
          { n: "Pescado blanco (tilapia/basa)", q: "2 filetes" },
          { n: "Atún en lata", q: "1 lata" },
          { n: "Garbanzos", q: "1 lata o 200 g" },
          { n: "Queso panela", q: "200 g" },
          { n: "Queso cottage", q: "200 g" },
          { n: "Jamón de pavo", q: "200 g" },
          { n: "Yogur griego natural", q: "1 kg" },
          { n: "Kefir (o leche para kefir)", q: "1 L" },
          { n: "Huevo", q: "1 docena" },
          { n: "Frijol", q: "1 lata o 250 g" },
        ]},
        { cat: "Verduras 🥕", items: [
          { n: "Jitomate", q: "1.5 kg" },
          { n: "Tomate verde", q: "500 g" },
          { n: "Cebolla", q: "4 piezas" },
          { n: "Chile poblano", q: "2 piezas" },
          { n: "Chile serrano", q: "2 piezas" },
          { n: "Pimiento", q: "1 pieza" },
          { n: "Calabacita", q: "4 piezas" },
          { n: "Papa", q: "4 piezas" },
          { n: "Zanahoria", q: "500 g" },
          { n: "Ajo", q: "1 cabeza" },
          { n: "Cilantro", q: "1 manojo" },
          { n: "Aguacate", q: "3 piezas" },
          { n: "Lechuga", q: "1 pieza" },
          { n: "Pepino", q: "2 piezas" },
          { n: "Limones", q: "½ kg" },
        ]},
        { cat: "Carbohidratos 🌾", items: [
          { n: "Arroz", q: "1 kg" },
          { n: "Tortillas de maíz", q: "1 kg" },
          { n: "Avena", q: "500 g" },
          { n: "Pan integral", q: "1 paquete" },
          { n: "Tostadas horneadas", q: "1 paquete" },
        ]},
        { cat: "Frutas 🍓", items: [
          { n: "Fresas", q: "500 g" },
          { n: "Mango", q: "2 piezas" },
          { n: "Plátano", q: "6 piezas" },
          { n: "Manzana", q: "4 piezas" },
          { n: "Papaya o melón", q: "1 pieza" },
        ]},
        { cat: "Despensa 🧂", items: [
          { n: "Aceitunas y alcaparras", q: "1 frasco chico" },
          { n: "Comino", q: "si falta" },
          { n: "Chile en polvo", q: "si falta" },
          { n: "Canela molida", q: "si falta" },
          { n: "Crema de cacahuate", q: "si falta" },
        ]},
        { cat: "El gusto del sábado 🥐", items: [
          { n: "Pan dulce", q: "2 piezas" },
        ]},
      ],
    },
  ],
};
